### PR TITLE
Improve show -c display format

### PR DESCRIPTION
**Pull request by wolfrage76**

### CODE REVIEW

**Comment by TheTad** [comment]
Hello, could you please elaborate on the changes?
Thank you!

**Comment by wolfrage76** [comment]
It simply helps cleanup the show -c display.

You can compare the MELATI display vs the CALDERA display (with this change) here:
https://ifhya.com/peers/peerlist.txt

**Comment by TheTad** [comment]
Oh I love it! 
I'm afraid it could brake any cli parsing people might have in place and rely on.
I wish that change could be done in the upstream.
Did you try to approach Chia team with this patch?

**Comment by TheTad** [comment]
@wolfrage76  thanks for your contribution! Could you please contact me I'd like to send you a tad reward!

**Comment by JumpinJon** [comment]
This is a really nice update, compared to the chaotic default Chia output.  However, I agree that it may cause problems for existing parsing code.  Perhaps this should be an additional option; perhaps --compact could supplement the existing -c option.

**Pull request merged**
